export const badgeReport = Array.from({ length: 20 }, (_, index) => ({
    id: `B-${1000 + index}`,
    email: `user${index + 1}@example.com`,
    user_name: `User ${index + 1}`,
    video_title: `Lesson ${index + 1}: Advanced Concepts`,
    course_name: [
        "React Developer Bootcamp",
        "Python for Data Science",
        "AI and Machine Learning",
        "Cybersecurity Essentials",
        "Full-Stack Web Development",
    ][index % 5],
    badge_name: [
        "React Master",
        "Python Data Analyst",
        "AI Specialist",
        "Cybersecurity Expert",
        "Full-Stack Developer",
    ][index % 5],
    badge_type: ["New", "Popular", "Trending", "Future Ready"][index % 4], // Categorization
    status: index % 2 === 0 ? "Awarded" : "Pending",
    criteria_met: index % 2 === 0 ? "Completed all course modules & quizzes" : "Incomplete quizzes",
    issue_date: index % 2 === 0 ? `2024-03-${(index % 28) + 1}` : "N/A",
    expiry_date: index % 2 === 0 ? `2026-03-${(index % 28) + 1}` : "N/A",
    score: index % 2 === 0 ? `${70 + (index % 30)}%` : "N/A",
    completion_time: index % 2 === 0 ? `${10 + (index % 10)} hours` : "N/A",
    instructor: [
        "John Doe",
        "Jane Smith",
        "Michael Lee",
        "Sarah Connor",
        "David Miller",
    ][index % 5],
    platform: index % 2 === 0 ? "Udemy" : "Coursera",
    badge_url: `https://certificates.example.com/badges/${1000 + index}`,
    verification_link: `https://certificates.example.com/verify/${1000 + index}`,
    shareable_on: ["LinkedIn", "Twitter", "Facebook"],
    attempts: Math.floor(Math.random() * 3) + 1,
    course_progress: `${Math.floor(Math.random() * 100)}%`,
    badge_description: "Awarded for completing the course and passing the final assessment with a minimum of 70%.",
    endorsement: index % 2 === 0 ? "Verified by Platform" : "Pending Verification",
}));
