export const corporateUserData = Array.from({ length: 50 }, (_, index) => ({
    key: (index + 1).toString(),
    name: `Employee ${index + 1}`,
    email: `employee${index + 1}@company.com`,
    phone: `90000000${index}`,
    company_name: `Company ${index % 5 + 1}`,
    department: ["IT", "HR", "Finance", "Marketing", "Operations"][index % 5],
    designation: ["Intern", "Executive", "Manager", "Director", "VP"][index % 5],
    years_of_experience: index % 15,
    team: `Team-${(index % 3) + 1}`,
    employment_type: index % 2 === 0 ? "Full-Time" : "Contract",
    learning_preference: index % 2 === 0 ? "Self-Paced" : "Instructor-Led",
    last_login: `2025-03-${(index % 28) + 1}`,
    subscription: {
        type: index % 3 === 0 ? "Enterprise Premium" : "Corporate Basic",
        status: index % 2 === 0 ? "Active" : "Expired",
        start_date: `2024-01-${(index % 28) + 1}`,
        end_date: `2025-01-${(index % 28) + 1}`,
        renewal_history: Array.from({ length: 2 }, (_, renewIndex) => ({
            date: `202${renewIndex}-12-15`,
            amount: `$${Math.floor(Math.random() * 500)}`,
            payment_method: ["Credit Card", "Corporate Wallet", "Bank Transfer"][renewIndex % 3],
            discount_applied: renewIndex % 2 === 0 ? "10% Bulk Discount" : "No Discount",
        }))
    },
    courses_enrolled: Array.from({ length: (index % 4) + 1 }, (_, courseIndex) => ({
        course_id: `C10${courseIndex + 1}`,
        course_name: `Advanced Course ${courseIndex + 1}`,
        progress: Math.floor(Math.random() * 100),
        completion_status: Math.random() > 0.5 ? "Completed" : "In Progress",
        quiz_scores: Array.from({ length: 3 }, () => Math.floor(Math.random() * 100)),
        last_activity: `2025-03-${(index % 28) + 1}`,
        project_submitted: Math.random() > 0.6 ? "Yes" : "No",
        peer_reviews_received: Math.floor(Math.random() * 5),
    })),
    total_watch_time: Math.floor(Math.random() * 500),
    learning_streak_days: index % 15,
    discussion_forum_activity: {
        questions_asked: Math.floor(Math.random() * 10),
        answers_given: Math.floor(Math.random() * 15),
        upvotes_received: Math.floor(Math.random() * 50),
    },
    mentorship_engagement: {
        mentor_assigned: Math.random() > 0.7 ? `Mentor-${index % 5}` : "None",
        sessions_attended: Math.floor(Math.random() * 5),
        feedback_score: Math.random() > 0.5 ? (Math.random() * 5).toFixed(1) : "N/A",
    },
    certifications_earned: Array.from({ length: index % 3 }, (_, certIndex) => ({
        certification_id: `Cert-${certIndex + 1}`,
        name: `Certified in ${["Python", "Data Science", "Machine Learning"][certIndex % 3]}`,
        issued_date: `2025-02-${(certIndex % 28) + 1}`,
        validity: "Lifetime",
    })),
    admin_feedback: index % 3 === 0 ? "Requires more participation in training programs." : "Good progress in upskilling.",
    company_learning_budget_utilization: {
        allocated_budget: "$5000",
        spent: `$${Math.floor(Math.random() * 5000)}`,
        remaining: `$${Math.floor(Math.random() * 2000)}`,
    },
    wishlist: ["Advanced Course A", "AI Fundamentals", "Leadership Skills"].slice(0, (index % 3) + 1),
}));